### ISSUE TITLE
Correct test?

### ISSUE THREAD

**Issue by tomato42** [khimaros/raid-explorations#2]
I did test the dm-integrity with raid too ([my blog post](https://securitypitfalls.wordpress.com/2018/05/08/raid-doesnt-work/)) and have come to a completely opposite conclusion: that dm-integrity does help to protect against silent corruption.

As far as I can tell from the errors you quoted, the issue may be in the test damaging dm-integrity metadata and/or journal (or mdadm superblocks). In such cases, the recovery is much more complex than just "assemble and resync", but it's not any different than without dm-integrity. If you damage the mdadm superblock, the array won't assemble either. 10GiB partitions also make it particularly likely that the corruption will hit the dm-integrity journal instead of the data or checksum block (for a 1.5TiB partition integritysetup used a 64MiB journal).

What happens when in case of issues mounting the dm-integrity you open it with `--integrity-no-journal` option?

(Side note: having dealt with multiple failing hard drives, I've never seen a failure mode in which the read would change just one byte in a sector. When silent corruption occurred the whole sector contained more-or-less random data).

**Comment by khimaros** [comment]
@tomato42 -- thank you for the feedback.

As explained in the README.md, reattaching the dm-integrity device with `--integrity-no-journal` still does not allow the device to be reattached to the MD array:

```
# integritysetup open --integrity sha256 -D -R /dev/sda3 sda3_int
# mdadm --manage /dev/md0 --add /dev/mapper/sda3_int
[ ... ] Buffer I/O error on dev dm-3, logical block 1, async page write
```

The only way to reattach that I found is to format and recreate the integrity device from scratch.

Do you happen to know where, precisely, the DM metadata would be on a 10GB device? In my tests I am skipping the first 20MB and last 16MB of the device to avoid metadata corruption.

Broadly, if you have an idea for a better way to simulate disk corruption I'm very open to pull requests.

**Comment by tomato42** [comment]
> @tomato42 -- thank you for the feedback.
> 
> As explained in the README.md, reattaching the dm-integrity device with `--integrity-no-journal` still does not allow the device to be reattached to the MD array. The only way to reattach that I found is to format and recreate the integrity device from scratch.

ah, sorry, didn't notice that; that would suggest a bug in dm-integrity though; If we tell it to ignore journal, it should ignore it...
 
> Do you happen to know where, precisely, the DM metadata would be on a 10GB device? In my tests I am skipping the first 20MB and last 16MB of the device to avoid metadata corruption.

actually, it seems like the journal size is independent of the size of the device, a quick check like this:
```
truncate -s 10G int-phys
integritysetup format --no-wipe --integrity sha256 int-phys
hexdump -C int-phys
```
shows that the last non-zero byte is at offset 0x03ffbfff, which is very close to the 64MiB size of the 1.5TiB device

So it looks like for dm-integrity, the first 64MiB of the device are special

> Broadly, if you have an idea for a better way to simulate disk corruption I'm very open to pull requests.

I think only increasing the skips to something like 0.5GiB should be sufficient (see also `mdadm --examine /dev/mapper/sda3_int | grep Data\ Offset`)

**Comment by tomato42** [comment]
One more thing about `mdadm --manage /dev/md0 --add /dev/mapper/sda3_int`: mdadm looks for superblock in all the places a superblock can be (i.e. the beginning of the disk, 4K from start and the end of disk, representing the metadata formats 1.1, 1.2 or 1.0 respectively), so if the blocks where the md-raid metadata *can* be are damaged the `--add` operation will fail too. 
You can overriding that behaviour by specifying the correct `--metadata=` option while adding the volume.

**Comment by khimaros** [comment]
> One more thing about `mdadm --manage /dev/md0 --add /dev/mapper/sda3_int`: mdadm looks for superblock in all the places a superblock can be (i.e. the beginning of the disk, 4K from start and the end of disk, representing the metadata formats 1.1, 1.2 or 1.0 respectively), so if the blocks where the md-raid metadata _can_ be are damaged the `--add` operation will fail too.
> You can overriding that behaviour by specifying the correct `--metadata=` option while adding the volume.

It sounds like this should not be a constraint with the approach you recommended above: skipping the first 512MB and final 128MB of the disk.

**Comment by tomato42** [comment]
yes, optimally, you should query dm-integrity how big is the journal and then query mdadm how big is the data offset

but then, do we have a reason to believe that mdadm and dm-integrity will handle a read error and checksum failure differently in first sector than in a millionth one? It's easier to just do "large enough" skip than to calculate exact value

**Comment by khimaros** [comment]
> but then, do we have a reason to believe that mdadm and dm-integrity will handle a read error and checksum failure in first sector than in a millionth one? It's easier to just do "large enough" skip than to calculate exact value

I'm not too concerned about the difficulty and have updated `random_write.py` to use 512MB offset at start and 128MB for end. A further improvement would be to corrupt entire sectors rather than random byte locations.

I've also added a caveat to my notes that if using devicemapper based block devices, it is a *very* good idea to backup these areas. It's particularly important with dm-crypt devices where it is otherwise impossible to recover any data without healthy metadata.

**Comment by khimaros** [comment]
I've documented the behavior difference between 4.19 and 5.7 kernels in `README.md` along with a tabular overview, and have made the requested changes to `random_write.py`. I've also included configs for all explorations in the `explorations/` folder Closing this issue.
